version: '2.2'
services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work:rw
      - ./settings/local:/home/jovyan/.local:rw
      - ./settings/jupyter:/home/jovyan/.jupyter:rw
    command: start.sh jupyter lab --NotebookApp.token=''
    restart: always
 
