version: '2.2'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work:rw
      - ./.local:/home/jovyan/.local:rw
      - ./.nbconfig:/home/jovyan/.jupyter/nbconfig:rw
    command: start-notebook.sh --NotebookApp.token=''
    restart: always
 
